<?xml version="1.0" encoding="utf-8"?><Database Name="ExpSys" Class="ExpDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SLAVA-PC\SQLEXPRESS;Initial Catalog=ExpSys;Integrated Security=True" SettingsObjectName="ExpertTest.Properties.Settings" SettingsPropertyName="ExpSysConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Shown" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Book_Property" Member="Properties" ThisKey="Id" OtherKey="BookId" Type="Property" />
    </Type>
  </Table>
  <Table Name="dbo.Dict" Member="Dicts">
    <Type Name="Dict">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Property" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ExpertStatistics" Member="ExpertStatistics">
    <Type Name="ExpertStatistic">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_ExpertStatistic" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.PropertyQuestion" Member="PropertyQuestions">
    <Type Name="PropertyQuestion">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="PropertyName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PropertyQuestion_AnswerWeight" Member="AnswerWeights" ThisKey="Id" OtherKey="QuestionId" Type="AnswerWeight" />
    </Type>
  </Table>
  <Table Name="dbo.PropertyWeight" Member="PropertyWeights">
    <Type Name="PropertyWeight">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Value" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PropertyName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserBook" Member="UserBooks">
    <Type Name="UserBook">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PropetyID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_UserBook" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="SET DEFAULT" />
    </Type>
  </Table>
  <Table Name="dbo.UserProperty" Member="UserProperties">
    <Type Name="UserProperty">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="User_UserProperty" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.UserQuestion" Member="UserQuestions">
    <Type Name="UserQuestion">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="User_UserQuestion" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AnswerWeight" Member="AnswerWeights">
    <Type Name="AnswerWeight">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Counter" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Type="System.Single" DbType="Real NOT NULL" CanBeNull="false" />
      <Column Name="DefaultWeight" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="PropertyQuestion_AnswerWeight" Member="PropertyQuestion" ThisKey="QuestionId" OtherKey="Id" Type="PropertyQuestion" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Admin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Ban" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="User_ExpertStatistic" Member="ExpertStatistics" ThisKey="Id" OtherKey="UserId" Type="ExpertStatistic" />
      <Association Name="User_UserBook" Member="UserBooks" ThisKey="Id" OtherKey="UserId" Type="UserBook" />
      <Association Name="User_UserProperty" Member="UserProperties" ThisKey="Id" OtherKey="UserId" Type="UserProperty" />
      <Association Name="User_UserQuestion" Member="UserQuestions" ThisKey="Id" OtherKey="UserId" Type="UserQuestion" />
      <Association Name="User_Weight" Member="Weights" ThisKey="Id" OtherKey="UserId" Type="Weight" />
    </Type>
  </Table>
  <Table Name="dbo.Weight" Member="Weights">
    <Type Name="Weight">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PropertyName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Weight" Member="Weight1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PropertyValue" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="User_Weight" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Property" Member="Properties">
    <Type Name="Property">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BookId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Value" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Shown" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Information" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NextQuestion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Book_Property" Member="Book" ThisKey="BookId" OtherKey="Id" Type="Book" IsForeignKey="true" />
    </Type>
  </Table>
</Database>